package com.example.employeemanager.repository;

import com.example.employeemanager.entity.Employee;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Repository interface for Employee entity.
 * 
 * Extends JpaRepository to automatically inherit full CRUD operations:
 * - save()
 * - findAll()
 * - findById()
 * - deleteById()
 * - count(), existsById(), and many pagination/sorting features.
 * 
 * Spring automatically registers this as a Bean at startup.
 */
@Repository
public interface EmployeeRepository extends JpaRepository<Employee, Long> {
    
    /**
     * Custom finder method generated by Spring Data JPA's query creation mechanism.
     * Generates a SELECT query to check if an employee exists with the given email.
     * 
     * @param email The email to search for
     * @return boolean True if an employee exists, False otherwise
     */
    boolean existsByEmail(String email);
    
    /**
     * Helper to verify if an email belongs to a different employee ID (useful for updates).
     */
    boolean existsByEmailAndIdNot(String email, Long id);
}
